#!/usr/bin/env python3
"""
PRADAKO — PRODUCT DETAIL PAGE GENERATOR
=======================================

WHY THIS EXISTS
---------------
Before this, every product's `url` field was empty. 277 products shared exactly
one landing page, which meant:

  - No page could rank for "DIN 933 hex bolt manufacturer India". Competitors
    (Bossard, Wurth, Fastenal) have a page per SKU and take that traffic.
  - There was no URL to paste into an email, an RFQ, or a WhatsApp message.
  - There was no schema.org/Product markup anywhere on the site, so Google had
    nothing structured to read.

This script generates one static page per product from the same catalogue the
gallery uses, so the data can never drift between the two.

    python3 tools/build_product_pages.py

Reads  : js/customised-products-data.js   (generated by build_catalog.py)
Writes : products/<product-id>.html       (277 files)
         products/index.html              (A-Z index of everything)

RUN build_catalog.py FIRST. This script reads its output.

Each page carries:
  - full specification table (standards, cross-reference, drive, head, thread,
    grades, materials, finishes, size range, sectors, testing)
  - schema.org/Product + BreadcrumbList JSON-LD
  - the shared enquiry basket and compare tray
  - deep links into the engineering calculators
  - related products from the same sub-type
  - canonical link and Open Graph tags
"""

import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT_DIR = os.path.join(ROOT, "products")

SITE = "https://www.pradako.co"
CANONICAL_BASE = SITE + "/products/"


def esc(value):
    return (str(value or "")
            .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def load_catalog():
    """Evaluate the generated JS data file via node and hand back JSON."""
    data_path = os.path.join(ROOT, "js", "customised-products-data.js")
    script = (
        "global.window={};require(%s);"
        "process.stdout.write(JSON.stringify(window.PMEW_CUSTOM_PRODUCT_CATALOG));"
        % json.dumps(data_path)
    )
    raw = subprocess.check_output(["node", "-e", script])
    return json.loads(raw)


# =============================================================================
#  PAGE TEMPLATE
# =============================================================================

PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{name} — {family} | Pradako Mechanical &amp; Engineering Works</title>
<meta name="description" content="{meta_desc}">
<link rel="canonical" href="{canonical}">

<meta property="og:type" content="product">
<meta property="og:title" content="{name} — Pradako">
<meta property="og:description" content="{meta_desc}">
<meta property="og:url" content="{canonical}">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700;800;900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="../css/products.css">
<link rel="stylesheet" href="../css/pradako-enquiry-cart.css">
<link rel="stylesheet" href="../css/pradako-products-plus.css">

<script type="application/ld+json">
{jsonld}
</script>
</head>
<body class="pmew-product-page">

<main class="pmew-pd-wrap">

  <nav class="pmew-pd-crumb" aria-label="Breadcrumb">
    <a href="../customised-products.html">Customised Products</a>
    <span aria-hidden="true">&rsaquo;</span>
    <a href="../{family_page}">{family}</a>
    <span aria-hidden="true">&rsaquo;</span>
    <a href="../customised-products.html?family={family_slug}&amp;type={subtype_slug}">{crumb_leaf}</a>
    <span aria-hidden="true">&rsaquo;</span>
    <strong>{name}</strong>
  </nav>

  <header class="pmew-pd-hero">
    <div class="pmew-pd-media">{media}</div>

    <div class="pmew-pd-intro">
      {partno_block}
      <span class="pmew-pd-eyebrow">{family} &middot; {category}</span>
      <h1 class="pmew-pd-title">{name}{provisional}</h1>
      <p class="pmew-pd-lead">{lead}</p>

      <div class="pmew-pd-keyspecs">{keyspecs}</div>

      <div class="pmew-pd-actions">
        <button type="button" class="pmew-card-enquiry pmew-pd-enquiry"
                data-enquiry-id="{pid}"
                data-enquiry-name="{name}"
                data-enquiry-category="{category}"
                data-enquiry-family="{family}"
                data-enquiry-family-url="../{family_page}"
                data-enquiry-image="{image}">
          <span data-enquiry-icon></span>
          <span data-enquiry-label>Add to Enquiry</span>
        </button>
        <a class="pmew-pd-secondary" href="../customised-products.html?family={family_slug}&amp;type={subtype_slug}">
          Browse all {subtype}
        </a>
      </div>

      <p class="pmew-pd-source">{source_note}</p>
    </div>
  </header>

  <section class="pmew-pd-section">
    <h2>Specification</h2>
    <table class="pmew-pd-table">
      <tbody>
{spec_rows}
      </tbody>
    </table>
  </section>

{crossref_block}
{tools_block}
{related_block}

  <section class="pmew-pd-cta">
    <div>
      <h2>Need this to your drawing?</h2>
      <p>Pradako has manufactured precision fasteners since 1961 across 7 plants
         and 16 divisions, supplying automotive, defence, aerospace, railway,
         electronics and solar customers on six continents. Send us your
         drawing, sample or specification and we will quote against it.</p>
    </div>
    <div class="pmew-pd-cta-actions">
      <button type="button" class="pmew-pd-cta-btn" data-open-enquiry>
        Open Enquiry Basket <span data-cart-badge>0/10</span>
      </button>
      <a class="pmew-pd-cta-link" href="../customised-products.html#product-type-enquiry">
        Send a custom requirement
      </a>
    </div>
  </section>

</main>

<script defer src="../js/pradako-enquiry-cart.js"></script>
<script defer src="../js/pradako-compare.js"></script>
</body>
</html>
"""


def spec_row(label, value):
    if isinstance(value, list):
        value = " &middot; ".join(esc(v) for v in value if v)
    else:
        value = esc(value)
    if not value:
        return ""
    return ("        <tr><th scope=\"row\">%s</th><td>%s</td></tr>\n"
            % (esc(label), value))


def build_page(product, family, group, siblings):
    attrs = product.get("attributes", {}) or {}
    pid = product["id"]
    name = product["name"]
    subtype = product.get("subType", "Fasteners")
    subtype_slug = re.sub(r"[^a-z0-9]+", "-", subtype.lower()).strip("-")

    standards = attrs.get("standards", [])
    grades = attrs.get("grades", [])

    lead_bits = []
    if standards:
        lead_bits.append("manufactured to " + ", ".join(standards[:3]))
    if grades:
        lead_bits.append("in " + " / ".join(grades[:4]))
    if attrs.get("sizeRange"):
        lead_bits.append("covering " + attrs["sizeRange"])

    lead = ("%s %s, %s." % (name, subtype.lower().rstrip("s"), "; ".join(lead_bits))
            if lead_bits else
            "%s manufactured to customer drawing by Pradako." % name)

    meta_desc = ("%s%s — %s. %s. Manufactured by Pradako Mechanical & Engineering "
                 "Works, Mumbai, since 1961." %
                 ((product.get("partNo", "") + " ") if product.get("partNo") else "",
                  name,
                  ", ".join(standards[:3]) if standards else family["name"],
                  attrs.get("sizeRange", "Sizes to drawing")))[:300]

    image = product.get("image", "")
    if image.startswith("images/"):
        image = "../" + image

    media = ('<img src="%s" alt="%s" loading="eager">' % (esc(image), esc(name))
             if image else
             '<span class="pmew-pd-media-blank">%s</span>' % esc(name))

    keyspecs = "".join(
        '<span class="pmew-pd-keyspec"><small>%s</small><strong>%s</strong></span>'
        % (esc(k), esc(v))
        for k, v in [
            ("Standard", standards[0] if standards else "To drawing"),
            ("Grade", " / ".join(grades[:2]) if grades else "On request"),
            ("Drive", attrs.get("drive", "On request")),
            ("Size range", attrs.get("sizeRange", "On request")),
        ] if v
    )

    spec_rows = "".join([
        spec_row("Pradako part number", product.get("partNo", "")),
        spec_row("Product type", subtype),
        spec_row("Category", group["type"]),
        spec_row("Family", family["name"]),
        spec_row("Standards", standards),
        spec_row("Drive", attrs.get("drive")),
        spec_row("Head form", attrs.get("head")),
        spec_row("Thread", attrs.get("threadType")),
        spec_row("Property class / grade", grades),
        spec_row("Materials", attrs.get("materials")),
        spec_row("Finishes", attrs.get("finishes")),
        spec_row("Size range", attrs.get("sizeRange")),
        spec_row("Sectors served", attrs.get("sectors")),
        spec_row("Testing", attrs.get("tests")),
    ])

    crossref = attrs.get("crossRef", [])
    crossref_block = ""
    if crossref:
        crossref_block = (
            '  <section class="pmew-pd-section">\n'
            '    <h2>Standard cross-reference</h2>\n'
            '    <p class="pmew-pd-note">Equivalent and near-equivalent designations. '
            'Confirm dimensional equivalence against the governing standard before substitution.</p>\n'
            '    <ul class="pmew-pd-xref">\n'
            + "".join('      <li>%s</li>\n' % esc(x) for x in crossref)
            + '    </ul>\n  </section>\n'
        )

    tools = product.get("tools", [])
    tools_block = ""
    if tools:
        tools_block = (
            '  <section class="pmew-pd-section">\n'
            '    <h2>Engineering tools for this product</h2>\n'
            '    <div class="pmew-pd-tools">\n'
            + "".join('      <a class="pmew-pd-tool" href="../%s"><strong>%s</strong></a>\n'
                      % (esc(t["url"]), esc(t["label"])) for t in tools)
            + '    </div>\n  </section>\n'
        )

    related = [s for s in siblings if s["id"] != pid][:8]
    related_block = ""
    if related:
        related_block = (
            '  <section class="pmew-pd-section">\n'
            '    <h2>Related %s</h2>\n'
            '    <div class="pmew-pd-related">\n' % esc(subtype.lower())
            + "".join('      <a href="%s.html">%s</a>\n' % (esc(r["id"]), esc(r["name"]))
                      for r in related)
            + '    </div>\n  </section>\n'
        )

    source_note = {
        "verified": "Specification verified by Pradako works engineering.",
        "derived": ("Specification compiled from the governing published standards. "
                    "Confirm critical dimensions with our engineering team before ordering."),
    }.get(product.get("source"),
          "Family-level specification. Contact us for the exact product data sheet.")

    jsonld = json.dumps({
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "Product",
                "name": name,
                "sku": product.get("partNo", ""),
                "mpn": product.get("partNo", ""),
                "description": meta_desc,
                "category": "%s > %s > %s" % (family["name"], group["type"], subtype),
                "url": CANONICAL_BASE + pid + ".html",
                "brand": {"@type": "Brand", "name": "Pradako"},
                "manufacturer": {
                    "@type": "Organization",
                    "name": "Pradako Mechanical & Engineering Works",
                    "foundingDate": "1961",
                    "address": {"@type": "PostalAddress",
                                "addressLocality": "Mumbai",
                                "addressCountry": "IN"}
                },
                "material": ", ".join(attrs.get("materials", [])[:3]),
                "additionalProperty": [
                    {"@type": "PropertyValue", "name": k,
                     "value": ", ".join(v) if isinstance(v, list) else str(v)}
                    for k, v in [
                        ("Standards", standards),
                        ("Grade", grades),
                        ("Drive", attrs.get("drive")),
                        ("Head form", attrs.get("head")),
                        ("Thread", attrs.get("threadType")),
                        ("Size range", attrs.get("sizeRange")),
                        ("Finishes", attrs.get("finishes")),
                    ] if v
                ]
            },
            {
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {"@type": "ListItem", "position": 1, "name": "Customised Products",
                     "item": SITE + "/customised-products.html"},
                    {"@type": "ListItem", "position": 2, "name": family["name"],
                     "item": SITE + "/" + family.get("url", "")},
                    {"@type": "ListItem", "position": 3, "name": name,
                     "item": CANONICAL_BASE + pid + ".html"},
                ]
            }
        ]
    }, indent=1, ensure_ascii=False)

    return PAGE.format(
        name=esc(name),
        pid=esc(pid),
        family=esc(family["name"]),
        family_slug=esc(family["slug"]),
        family_page=esc(family.get("url", "customised-products.html")),
        category=esc(group["type"]),
        subtype=esc(subtype),
        subtype_slug=esc(subtype_slug),
        partno_block=('<span class="pmew-pd-partno">%s</span>' % esc(product.get("partNo", ""))
                      if product.get("partNo") else ''),
        crumb_leaf=esc(group["type"] if subtype.lower() == family["name"].lower().rstrip("s") + "s"
                       or subtype.lower() == family["name"].lower() else subtype),
        canonical=CANONICAL_BASE + pid + ".html",
        meta_desc=esc(meta_desc),
        lead=esc(lead),
        media=media,
        image=esc(image),
        keyspecs=keyspecs,
        spec_rows=spec_rows,
        crossref_block=crossref_block,
        tools_block=tools_block,
        related_block=related_block,
        source_note=esc(source_note),
        provisional=(' <span class="pmew-provisional-badge">Provisional</span>'
                     if product.get("provisional") else ''),
        jsonld=jsonld,
    )


def main():
    catalog = load_catalog()
    os.makedirs(OUT_DIR, exist_ok=True)

    by_subtype = {}
    flat = []
    for family in catalog:
        for group in family["groups"]:
            for product in group["productItems"]:
                key = (family["slug"], product.get("subType"))
                by_subtype.setdefault(key, []).append(product)
                flat.append((product, family, group, key))

    written = 0
    for product, family, group, key in flat:
        html = build_page(product, family, group, by_subtype[key])
        with open(os.path.join(OUT_DIR, product["id"] + ".html"), "w", encoding="utf-8") as fh:
            fh.write(html)
        written += 1

    # ---- remove pages whose product no longer exists ---------------------
    # A rename (e.g. "Trox Screws" -> "Torx Screws / Six Lobe") changes the id
    # and therefore the filename. Without this sweep the old page survives as a
    # dead URL that still ranks and still shows the old spelling.
    live = {p["id"] + ".html" for p, f, g, k in flat}
    live.add("index.html")
    removed = 0
    for name in os.listdir(OUT_DIR):
        if name.endswith(".html") and name not in live:
            os.remove(os.path.join(OUT_DIR, name))
            removed += 1
    if removed:
        print("Removed %d orphaned page(s)" % removed)

    # ---- A-Z index -------------------------------------------------------
    rows = sorted(((p["name"], p["id"], f["name"], p.get("subType", ""))
                   for p, f, g, k in flat), key=lambda r: r[0].lower())

    index = ["<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">",
             "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
             "<title>All Products A&ndash;Z | Pradako</title>",
             "<link rel=\"stylesheet\" href=\"../css/products.css\">",
             "<link rel=\"stylesheet\" href=\"../css/pradako-products-plus.css\">",
             "</head><body class=\"pmew-product-page\"><main class=\"pmew-pd-wrap\">",
             "<nav class=\"pmew-pd-crumb\"><a href=\"../customised-products.html\">Customised Products</a>",
             "<span>&rsaquo;</span><strong>All products A&ndash;Z</strong></nav>",
             "<h1 class=\"pmew-pd-title\">All products A&ndash;Z</h1>",
             "<p class=\"pmew-pd-lead\">%d products across %d families.</p>" % (len(rows), len(catalog)),
             "<div class=\"pmew-pd-index\">"]

    for name, pid, fam, sub in rows:
        index.append('<a href="%s.html"><strong>%s</strong><small>%s &middot; %s</small></a>'
                     % (esc(pid), esc(name), esc(fam), esc(sub)))

    index.append("</div></main></body></html>")

    with open(os.path.join(OUT_DIR, "index.html"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(index))

    print("Wrote %d product pages + index to %s" % (written, OUT_DIR))


if __name__ == "__main__":
    main()
